language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
deploy:
  provider: s3
  access_key_id: AKIAJSMOSCU7OBBJICFQ
  secret_access_key:
    secure: LSOZz3+QYKLlCPlwKkcahNwyS1A12hTB0VDdZAUZUvanRMJRHTww6NTkEppUyqXWL0fzWo0X5/tjx9IE3YU5J5/ZAoeGqc4oQpd3ztnWPQynW7JUH06JIXudWodH2s9FkzDeemQUzkudhKiRKV1tDWNCCPwdlu7ROlCCGT1xYqUfmy/Y2Yc+S30fxLsStbmfbYS4+5pZ7vEOXrZZFHRhs1uKcTixTxPHEeCHAGfG91ZuOg5LWeMXwgt/aRI7fbQVhXQ5XBu8U9E1K7LFjW8XlTWxXvHdM9sB+TU8/Wyhx3vvcHEhSGGydv8enIBrPHDZmYOM8oNYfmIwQxrcamt9MBvQhKRuFISt8PsM92se/u9omYAl1z/gS9jjsZT11jguN+M2e+IND8ZiBJT6d8VuJd8OVBUeGlXNEVN9xBBzrBcWZuij7kSgY4pEFvCB4Vkup7uLFHOS7l0DEozAQ4yg+KPkXZiSflUXZvqd7zgN4GaJrdf4KwoPxd/izE6ka6QoGFafbdc8vDMgzTjAnHHSJ8QYWORVgzSZsXvwFLsxxOEL25xkgeNn/FgxMdW9KT8CIWb3YGh6aBTEsyrBjcEd/OVKX2tcM1x3HxRohfxzhfo/Mh3IfmLzI6Kgj9J2N3iRrldIWP2y+AbEgHSIfsHxIYhoYsBqO89A3aHEnBal4d8=
  bucket: tinypixelgame
  upload-dir: builds
  skip_cleanup: true

